# Generated by Django 6.0.6 on 2026-07-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='N/A', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('system_admin', 'system_admin'), ('merchant_admin', 'merchant_admin'), ('customer', 'customer')], max_length=100),
        ),
    ]
