# Generated by Django 6.0.6 on 2026-07-03 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
        ('users', '0002_user_full_name_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='related_merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='merchants.merchant'),
        ),
    ]
