# Generated by Django 6.0.6 on 2026-07-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='live_api_key',
            field=models.CharField(default='N/A', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchant',
            name='test_api_key',
            field=models.CharField(default='N/A', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchant',
            name='webhook_url',
            field=models.URLField(null=True),
        ),
    ]
