# Generated by Django 6.0.6 on 2026-07-05 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_merchant_live_api_key_merchant_test_api_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=40)),
                ('billing_interval', models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('annually', 'annually'), ('custom', 'custom')], max_length=100)),
                ('billing_interval_in_days', models.IntegerField(null=True)),
                ('trial_period_in_days', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=100, verbose_name=(('active', 'active'), ('inactive', 'inactive'), ('archived', 'archived')))),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.merchant')),
            ],
        ),
    ]
