# Generated by Django 6.0.6 on 2026-07-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0003_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='status',
            field=models.CharField(default='active', max_length=100, verbose_name=(('active', 'active'), ('inactive', 'inactive'), ('archived', 'archived'))),
        ),
    ]
